
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"  # Look for `package.json` and `lock` files in the `root` directory
    schedule:
      interval: "daily"
