# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: material_database.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'material_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17material_database.proto\"\xab\x01\n\x08Material\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08shortkey\x18\x02 \x01(\t\x12\x0f\n\x07safekey\x18\x03 \x01(\t\x12\x14\n\x0cncmat_header\x18\x04 \x03(\t\x12\x0c\n\x04\x64ump\x18\x05 \x01(\t\x12\x16\n\x0encmat_contents\x18\x06 \x01(\t\x12\x1b\n\x13plot_filename_xsect\x18\x07 \x01(\t\x12\x16\n\x0e\x65xtra_keywords\x18\x08 \x01(\t\"(\n\x08\x44\x61tabase\x12\x1c\n\tmaterials\x18\x01 \x03(\x0b\x32\t.Materialb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'material_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATERIAL']._serialized_start=28
  _globals['_MATERIAL']._serialized_end=199
  _globals['_DATABASE']._serialized_start=201
  _globals['_DATABASE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
